### PR TITLE
Added 7 altcoins

### PR DESCRIPTION
**Pull request by ancilcleetus**
I have found that many altcoins already added don't have testnet info eventhough
it is present in the net.cpp file or chainparams.cpp file.
Hence I have added updated versions of those coins also.
Coins added:

007coin
2give
365coin
808coin
spec
accoladecoin
acoin

### CODE REVIEW

**Comment by StuartFarmer** [comment]
if there are no DNS seed addresses, a testnet does not exist / can not be utilized

**Comment by ancilcleetus** [comment]
Got it...

And where should I add my eth address?

**Comment by StuartFarmer** [comment]
you can leave it here and I will use it for all of your PRs

**Comment by ancilcleetus** [comment]
Thank you Stuart.

My eth address: 0x42c9af8954880d1B0ad86a537b08a837139a5cde

Added coins:
1.	abjcoin
2.	acescoin
3.	agrolifecoin
4.	alqo
5.	ammo
6.	anarchists_prime
7.	antimatter
8.	atmos
9.	b3coin
10.	birds
11.	digital_money_bits
12.	era
13.	muecoin
14.	syndicate
15.	superbitcoin
16.	topazcoin
17.	trollcoin
18.	trustplus
19.	wager
20.	yenten
21.	solarflarecoin
22.	strike_bit_club
23.	supernet

**Pull request merged**
